### PR TITLE
Hotfix for mainOutput is null error log

### PR DESCRIPTION
**Pull request by rickygv99**
Hotfix for following error:

`TypeError: Cannot read property 'mainOutput' of null
   at displayResult (/Users/rickygv/GitHub/almond-server/node_modules/almond-dialog-agent/lib/dialogs/rule.js:130:57)
   at ruleDialog (/Users/rickygv/GitHub/almond-server/node_modules/almond-dialog-agent/lib/dialogs/rule.js:284:11)
   at process._tickCallback (internal/process/next_tick.js:68:7)`

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
This looks good as a quick fix, but the correct thing to do is:
- if the app is null, we display only "Consider it done"
Probably the fix should be inside displayResult

Also, we should add tests, by modifying test/mock.js `createApp`: if the program is remote (executor !== null) and there is no `return` clause, `createApp` returns `null`.

**Comment by gcampax** [comment]
Are you still working on this?

**Comment by rickygv99** [comment]
I forgot I had this pull request -- thanks for the reminder. I'll get on that right now.

**Review by gcampax — COMMENTED** [review]
Please change the mock implementation of createApp to return null if the app is fully remote (for testing). As you then fix the tests, you should notice that the current behavior is not quite right in terms of what the assistant says...

**Comment by rickygv99** [comment]
Is there any easy way of checking if the program has a return clause?

**Comment by gcampax** [comment]
I'm taking over this PR so we can get this fix in today.

**Pull request merged**
