### PR TITLE
Entity linking for entities with no values

### PR DESCRIPTION
**Pull request by gcampax**
The quote removal work generates entities with null value and non-null display, which should be linked correctly.

### CODE REVIEW

**Comment by gcampax** [comment]
I might actually do this properly before I merge it, and tests are missing.

**Comment by gcampax** [comment]
This PR will also fix https://github.com/Stanford-Mobisocial-IoT-Lab/almond-tokenizer/issues/3 (and consequently https://github.com/Stanford-Mobisocial-IoT-Lab/almond-cloud/issues/35 ) given that the tokenizer is no longer involved in entity resolution.

**Review by sileix — COMMENTED** [review]
Overall looks good. 
For tokensEquals, I feel stemming is probably too strong for entities, but maybe some weaker preprocess can be used, such as "singularize" (https://www.npmjs.com/package/pluralize)

**Comment by gcampax** [comment]
Thanks, `pluralize` is a good suggestion to consider for the future, although a bit problematic for i18n. Anyway let's merge this now.

**Pull request merged**
